package rpm.simulation;

import rpm.domain.VitalSnapshot;
import rpm.domain.VitalType;
import rpm.ecg.EcgGenerator;
import rpm.ecg.EcgsynGenerator;
import rpm.ecg.EcgRingBuffer;

import java.time.Instant;
import java.util.EnumMap;
import java.util.Map;

/**
 * Simulates a single patient.
 *
 * - Heart rate, respiratory rate, blood pressure, temperature
 *   are generated by the individual simulators.
 * - ECG is generated continuously by EcgGenerator (ECGSYN)
 *
 */
public class PatientSimulator {

    private final HeartRateSimulator heartRateSimulator;
    private final RespRateSimulator respRateSimulator;
    private final BloodPressureSimulator bloodPressureSimulator;
    private final TemperatureSimulator temperatureSimulator;

    private final double ecgSamplingFrequencyHz = 250.0;
    private final double ecgWindowSeconds = 4.0;

    private final EcgGenerator ecgGenerator;
    private final EcgRingBuffer ecgRingBuffer;


    private double[] lastEcgSegment = new double[0];

    /** Latest heart rate in bpm (used to drive ECGSYN) */
    private double lastHeartRateBpm = 75.0;

    public PatientSimulator() {
        this.heartRateSimulator = new HeartRateSimulator();
        this.respRateSimulator = new RespRateSimulator();
        this.bloodPressureSimulator = new BloodPressureSimulator();
        this.temperatureSimulator = new TemperatureSimulator();

        // ECG generator (ECGSYN)
        this.ecgGenerator = new EcgsynGenerator();

        // Ring buffer holds 4 seconds of ECG at 250 Hz ≈ 1000 samples
        int ecgWindowSamples = (int) Math.round(ecgSamplingFrequencyHz * ecgWindowSeconds);
        this.ecgRingBuffer = new EcgRingBuffer(ecgWindowSamples);
    }
    public VitalSnapshot nextSnapshot(Instant time) {
        Map<VitalType, Double> values = new EnumMap<>(VitalType.class);

        double heartRate = heartRateSimulator.nextValue(time);
        lastHeartRateBpm = heartRate;

        double respRate = respRateSimulator.nextValue(time);
        double systolic = bloodPressureSimulator.nextValue(time);
        double diastolic = bloodPressureSimulator.getCurrentDiastolic();
        double temperature = temperatureSimulator.nextValue(time);

        values.put(VitalType.HEART_RATE, heartRate);
        values.put(VitalType.RESP_RATE, respRate);
        values.put(VitalType.BP_SYSTOLIC, systolic);
        values.put(VitalType.BP_DIASTOLIC, diastolic);
        values.put(VitalType.TEMPERATURE, temperature);

        return new VitalSnapshot(time, values);
    }

    public void advanceEcg(double durationSeconds) {
        if (durationSeconds <= 0.0) {
            return;
        }

        double[] segment = ecgGenerator.generateSegment(
                durationSeconds,
                lastHeartRateBpm,
                ecgSamplingFrequencyHz
        );

        if (segment == null || segment.length == 0) {
            return;
        }

        lastEcgSegment = segment;
        ecgRingBuffer.append(segment);
    }

    public double[] getCurrentEcgWindow() {
        return ecgRingBuffer.getLatestWindow();
    }

    public double[] getLastEcgSegment() {
        return lastEcgSegment;
    }

    public double getEcgSamplingFrequencyHz() {
        return ecgSamplingFrequencyHz;
    }
}
